// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: api/v1/quiz/service.proto

package quiz

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_LANGUAGE_PYTHON      Language = 1
	Language_LANGUAGE_JAVASCRIPT  Language = 2
	Language_LANGUAGE_GO          Language = 3
	Language_LANGUAGE_JAVA        Language = 4
	Language_LANGUAGE_CPP         Language = 5
	Language_LANGUAGE_RUST        Language = 6
	Language_LANGUAGE_TYPESCRIPT  Language = 7
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "LANGUAGE_PYTHON",
		2: "LANGUAGE_JAVASCRIPT",
		3: "LANGUAGE_GO",
		4: "LANGUAGE_JAVA",
		5: "LANGUAGE_CPP",
		6: "LANGUAGE_RUST",
		7: "LANGUAGE_TYPESCRIPT",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"LANGUAGE_PYTHON":      1,
		"LANGUAGE_JAVASCRIPT":  2,
		"LANGUAGE_GO":          3,
		"LANGUAGE_JAVA":        4,
		"LANGUAGE_CPP":         5,
		"LANGUAGE_RUST":        6,
		"LANGUAGE_TYPESCRIPT":  7,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_quiz_service_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_api_v1_quiz_service_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{0}
}

type Difficulty int32

const (
	Difficulty_DIFFICULTY_UNSPECIFIED  Difficulty = 0
	Difficulty_DIFFICULTY_BEGINNER     Difficulty = 1
	Difficulty_DIFFICULTY_INTERMEDIATE Difficulty = 2
	Difficulty_DIFFICULTY_ADVANCED     Difficulty = 3
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "DIFFICULTY_UNSPECIFIED",
		1: "DIFFICULTY_BEGINNER",
		2: "DIFFICULTY_INTERMEDIATE",
		3: "DIFFICULTY_ADVANCED",
	}
	Difficulty_value = map[string]int32{
		"DIFFICULTY_UNSPECIFIED":  0,
		"DIFFICULTY_BEGINNER":     1,
		"DIFFICULTY_INTERMEDIATE": 2,
		"DIFFICULTY_ADVANCED":     3,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_quiz_service_proto_enumTypes[1].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_api_v1_quiz_service_proto_enumTypes[1]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{1}
}

type ListQuestions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQuestions) Reset() {
	*x = ListQuestions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestions) ProtoMessage() {}

func (x *ListQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestions.ProtoReflect.Descriptor instead.
func (*ListQuestions) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{0}
}

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Language    Language          `protobuf:"varint,2,opt,name=language,proto3,enum=quiz.Language" json:"language,omitempty"`
	Topic       string            `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Difficulty  Difficulty        `protobuf:"varint,4,opt,name=difficulty,proto3,enum=quiz.Difficulty" json:"difficulty,omitempty"`
	Content     *Question_Content `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Explanation string            `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Types that are assignable to Answer:
	//
	//	*Question_MultipleChoice
	//	*Question_FreeText
	Answer isQuestion_Answer `protobuf_oneof:"Answer"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *Question) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Question) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *Question) GetContent() *Question_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Question) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (m *Question) GetAnswer() isQuestion_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (x *Question) GetMultipleChoice() *Question_MultipleChoiceAnswer {
	if x, ok := x.GetAnswer().(*Question_MultipleChoice); ok {
		return x.MultipleChoice
	}
	return nil
}

func (x *Question) GetFreeText() *Question_FreeTextAnswer {
	if x, ok := x.GetAnswer().(*Question_FreeText); ok {
		return x.FreeText
	}
	return nil
}

type isQuestion_Answer interface {
	isQuestion_Answer()
}

type Question_MultipleChoice struct {
	MultipleChoice *Question_MultipleChoiceAnswer `protobuf:"bytes,7,opt,name=multiple_choice,json=multipleChoice,proto3,oneof"`
}

type Question_FreeText struct {
	FreeText *Question_FreeTextAnswer `protobuf:"bytes,8,opt,name=free_text,json=freeText,proto3,oneof"`
}

func (*Question_MultipleChoice) isQuestion_Answer() {}

func (*Question_FreeText) isQuestion_Answer() {}

type ListQuestions_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language   Language   `protobuf:"varint,1,opt,name=language,proto3,enum=quiz.Language" json:"language,omitempty"`
	Topics     []string   `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Difficulty Difficulty `protobuf:"varint,3,opt,name=difficulty,proto3,enum=quiz.Difficulty" json:"difficulty,omitempty"`
	Limit      uint32     `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListQuestions_Request) Reset() {
	*x = ListQuestions_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestions_Request) ProtoMessage() {}

func (x *ListQuestions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestions_Request.ProtoReflect.Descriptor instead.
func (*ListQuestions_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListQuestions_Request) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *ListQuestions_Request) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ListQuestions_Request) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *ListQuestions_Request) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListQuestions_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *ListQuestions_Response) Reset() {
	*x = ListQuestions_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestions_Response) ProtoMessage() {}

func (x *ListQuestions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestions_Response.ProtoReflect.Descriptor instead.
func (*ListQuestions_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ListQuestions_Response) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string  `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Code *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
}

func (x *Question_Content) Reset() {
	*x = Question_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question_Content) ProtoMessage() {}

func (x *Question_Content) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question_Content.ProtoReflect.Descriptor instead.
func (*Question_Content) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Question_Content) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question_Content) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type Question_MultipleChoiceAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options        []string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOptions []string `protobuf:"bytes,4,rep,name=correct_options,json=correctOptions,proto3" json:"correct_options,omitempty"`
}

func (x *Question_MultipleChoiceAnswer) Reset() {
	*x = Question_MultipleChoiceAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question_MultipleChoiceAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question_MultipleChoiceAnswer) ProtoMessage() {}

func (x *Question_MultipleChoiceAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question_MultipleChoiceAnswer.ProtoReflect.Descriptor instead.
func (*Question_MultipleChoiceAnswer) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Question_MultipleChoiceAnswer) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question_MultipleChoiceAnswer) GetCorrectOptions() []string {
	if x != nil {
		return x.CorrectOptions
	}
	return nil
}

type Question_FreeTextAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrectAnswers []string `protobuf:"bytes,1,rep,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
}

func (x *Question_FreeTextAnswer) Reset() {
	*x = Question_FreeTextAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_quiz_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question_FreeTextAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question_FreeTextAnswer) ProtoMessage() {}

func (x *Question_FreeTextAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question_FreeTextAnswer.ProtoReflect.Descriptor instead.
func (*Question_FreeTextAnswer) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Question_FreeTextAnswer) GetCorrectAnswers() []string {
	if x != nil {
		return x.CorrectAnswers
	}
	return nil
}

var File_api_v1_quiz_service_proto protoreflect.FileDescriptor

var file_api_v1_quiz_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x71, 0x75, 0x69,
	0x7a, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xc2, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x69, 0x7a,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x82, 0x01,
	0x04, 0x10, 0x01, 0x20, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x42,
	0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x44, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x82, 0x01, 0x04, 0x10,
	0x01, 0x20, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12,
	0x1f, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x2a, 0x04, 0x10, 0x0a, 0x20, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x1a, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd1, 0x04, 0x0a, 0x08, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x69, 0x7a,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x71, 0x75, 0x69, 0x7a, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x52,
	0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x71,
	0x75, 0x69, 0x7a, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x4e, 0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x54, 0x65, 0x78, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x3f, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x17, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0x59,
	0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x63, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x39, 0x0a, 0x0e, 0x46, 0x72, 0x65,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2a, 0xb4,
	0x01, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x4c,
	0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47,
	0x45, 0x5f, 0x50, 0x59, 0x54, 0x48, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x41,
	0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x5f, 0x4a, 0x41, 0x56, 0x41, 0x53, 0x43, 0x52, 0x49, 0x50,
	0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x5f,
	0x47, 0x4f, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45,
	0x5f, 0x4a, 0x41, 0x56, 0x41, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x41, 0x4e, 0x47, 0x55,
	0x41, 0x47, 0x45, 0x5f, 0x43, 0x50, 0x50, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41, 0x4e,
	0x47, 0x55, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x55, 0x53, 0x54, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13,
	0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x53, 0x43, 0x52,
	0x49, 0x50, 0x54, 0x10, 0x07, 0x2a, 0x77, 0x0a, 0x0a, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x49, 0x46, 0x46, 0x49, 0x43, 0x55, 0x4c, 0x54,
	0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x13, 0x44, 0x49, 0x46, 0x46, 0x49, 0x43, 0x55, 0x4c, 0x54, 0x59, 0x5f, 0x42, 0x45,
	0x47, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x49, 0x46, 0x46,
	0x49, 0x43, 0x55, 0x4c, 0x54, 0x59, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4d, 0x45, 0x44, 0x49,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x49, 0x46, 0x46, 0x49, 0x43, 0x55,
	0x4c, 0x54, 0x59, 0x5f, 0x41, 0x44, 0x56, 0x41, 0x4e, 0x43, 0x45, 0x44, 0x10, 0x03, 0x32, 0x6e,
	0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x66, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f,
	0x71, 0x75, 0x69, 0x7a, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x73,
	0x6e, 0x65, 0x72, 0x61, 0x6e, 0x6f, 0x2f, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x2d, 0x77,
	0x61, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75,
	0x69, 0x7a, 0x3b, 0x71, 0x75, 0x69, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_quiz_service_proto_rawDescOnce sync.Once
	file_api_v1_quiz_service_proto_rawDescData = file_api_v1_quiz_service_proto_rawDesc
)

func file_api_v1_quiz_service_proto_rawDescGZIP() []byte {
	file_api_v1_quiz_service_proto_rawDescOnce.Do(func() {
		file_api_v1_quiz_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_quiz_service_proto_rawDescData)
	})
	return file_api_v1_quiz_service_proto_rawDescData
}

var file_api_v1_quiz_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_quiz_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_quiz_service_proto_goTypes = []interface{}{
	(Language)(0),                         // 0: quiz.Language
	(Difficulty)(0),                       // 1: quiz.Difficulty
	(*ListQuestions)(nil),                 // 2: quiz.ListQuestions
	(*Question)(nil),                      // 3: quiz.Question
	(*ListQuestions_Request)(nil),         // 4: quiz.ListQuestions.Request
	(*ListQuestions_Response)(nil),        // 5: quiz.ListQuestions.Response
	(*Question_Content)(nil),              // 6: quiz.Question.Content
	(*Question_MultipleChoiceAnswer)(nil), // 7: quiz.Question.MultipleChoiceAnswer
	(*Question_FreeTextAnswer)(nil),       // 8: quiz.Question.FreeTextAnswer
}
var file_api_v1_quiz_service_proto_depIdxs = []int32{
	0, // 0: quiz.Question.language:type_name -> quiz.Language
	1, // 1: quiz.Question.difficulty:type_name -> quiz.Difficulty
	6, // 2: quiz.Question.content:type_name -> quiz.Question.Content
	7, // 3: quiz.Question.multiple_choice:type_name -> quiz.Question.MultipleChoiceAnswer
	8, // 4: quiz.Question.free_text:type_name -> quiz.Question.FreeTextAnswer
	0, // 5: quiz.ListQuestions.Request.language:type_name -> quiz.Language
	1, // 6: quiz.ListQuestions.Request.difficulty:type_name -> quiz.Difficulty
	3, // 7: quiz.ListQuestions.Response.questions:type_name -> quiz.Question
	4, // 8: quiz.Quiz.ListQuestions:input_type -> quiz.ListQuestions.Request
	5, // 9: quiz.Quiz.ListQuestions:output_type -> quiz.ListQuestions.Response
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_quiz_service_proto_init() }
func file_api_v1_quiz_service_proto_init() {
	if File_api_v1_quiz_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_quiz_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestions_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestions_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question_MultipleChoiceAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_quiz_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question_FreeTextAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_quiz_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Question_MultipleChoice)(nil),
		(*Question_FreeText)(nil),
	}
	file_api_v1_quiz_service_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_quiz_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_quiz_service_proto_goTypes,
		DependencyIndexes: file_api_v1_quiz_service_proto_depIdxs,
		EnumInfos:         file_api_v1_quiz_service_proto_enumTypes,
		MessageInfos:      file_api_v1_quiz_service_proto_msgTypes,
	}.Build()
	File_api_v1_quiz_service_proto = out.File
	file_api_v1_quiz_service_proto_rawDesc = nil
	file_api_v1_quiz_service_proto_goTypes = nil
	file_api_v1_quiz_service_proto_depIdxs = nil
}
