// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/quiz/service.proto

package quiz

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListQuestions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListQuestions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQuestions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListQuestionsMultiError, or
// nil if none found.
func (m *ListQuestions) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQuestions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListQuestionsMultiError(errors)
	}

	return nil
}

// ListQuestionsMultiError is an error wrapping multiple validation errors
// returned by ListQuestions.ValidateAll() if the designated constraints
// aren't met.
type ListQuestionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQuestionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQuestionsMultiError) AllErrors() []error { return m }

// ListQuestionsValidationError is the validation error returned by
// ListQuestions.Validate if the designated constraints aren't met.
type ListQuestionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQuestionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQuestionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQuestionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQuestionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQuestionsValidationError) ErrorName() string { return "ListQuestionsValidationError" }

// Error satisfies the builtin error interface
func (e ListQuestionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQuestions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQuestionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQuestionsValidationError{}

// Validate checks the field values on Question with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Question) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Question with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuestionMultiError, or nil
// if none found.
func (m *Question) ValidateAll() error {
	return m.validate(true)
}

func (m *Question) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Language

	// no validation rules for Topic

	// no validation rules for Difficulty

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QuestionValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QuestionValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QuestionValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Explanation

	switch v := m.Answer.(type) {
	case *Question_MultipleChoice:
		if v == nil {
			err := QuestionValidationError{
				field:  "Answer",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetMultipleChoice()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QuestionValidationError{
						field:  "MultipleChoice",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QuestionValidationError{
						field:  "MultipleChoice",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMultipleChoice()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QuestionValidationError{
					field:  "MultipleChoice",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Question_FreeText:
		if v == nil {
			err := QuestionValidationError{
				field:  "Answer",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFreeText()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QuestionValidationError{
						field:  "FreeText",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QuestionValidationError{
						field:  "FreeText",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFreeText()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QuestionValidationError{
					field:  "FreeText",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return QuestionMultiError(errors)
	}

	return nil
}

// QuestionMultiError is an error wrapping multiple validation errors returned
// by Question.ValidateAll() if the designated constraints aren't met.
type QuestionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuestionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuestionMultiError) AllErrors() []error { return m }

// QuestionValidationError is the validation error returned by
// Question.Validate if the designated constraints aren't met.
type QuestionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuestionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuestionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuestionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuestionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuestionValidationError) ErrorName() string { return "QuestionValidationError" }

// Error satisfies the builtin error interface
func (e QuestionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuestion.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuestionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuestionValidationError{}

// Validate checks the field values on ListQuestions_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListQuestions_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQuestions_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListQuestions_RequestMultiError, or nil if none found.
func (m *ListQuestions_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQuestions_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _ListQuestions_Request_Language_NotInLookup[m.GetLanguage()]; ok {
		err := ListQuestions_RequestValidationError{
			field:  "Language",
			reason: "value must not be in list [LANGUAGE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Language_name[int32(m.GetLanguage())]; !ok {
		err := ListQuestions_RequestValidationError{
			field:  "Language",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetTopics()) < 1 {
		err := ListQuestions_RequestValidationError{
			field:  "Topics",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _ListQuestions_Request_Difficulty_NotInLookup[m.GetDifficulty()]; ok {
		err := ListQuestions_RequestValidationError{
			field:  "Difficulty",
			reason: "value must not be in list [DIFFICULTY_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Difficulty_name[int32(m.GetDifficulty())]; !ok {
		err := ListQuestions_RequestValidationError{
			field:  "Difficulty",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetLimit(); val <= 0 || val >= 10 {
		err := ListQuestions_RequestValidationError{
			field:  "Limit",
			reason: "value must be inside range (0, 10)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListQuestions_RequestMultiError(errors)
	}

	return nil
}

// ListQuestions_RequestMultiError is an error wrapping multiple validation
// errors returned by ListQuestions_Request.ValidateAll() if the designated
// constraints aren't met.
type ListQuestions_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQuestions_RequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQuestions_RequestMultiError) AllErrors() []error { return m }

// ListQuestions_RequestValidationError is the validation error returned by
// ListQuestions_Request.Validate if the designated constraints aren't met.
type ListQuestions_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQuestions_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQuestions_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQuestions_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQuestions_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQuestions_RequestValidationError) ErrorName() string {
	return "ListQuestions_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListQuestions_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQuestions_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQuestions_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQuestions_RequestValidationError{}

var _ListQuestions_Request_Language_NotInLookup = map[Language]struct{}{
	0: {},
}

var _ListQuestions_Request_Difficulty_NotInLookup = map[Difficulty]struct{}{
	0: {},
}

// Validate checks the field values on ListQuestions_Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListQuestions_Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQuestions_Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListQuestions_ResponseMultiError, or nil if none found.
func (m *ListQuestions_Response) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQuestions_Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetQuestions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListQuestions_ResponseValidationError{
						field:  fmt.Sprintf("Questions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListQuestions_ResponseValidationError{
						field:  fmt.Sprintf("Questions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListQuestions_ResponseValidationError{
					field:  fmt.Sprintf("Questions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListQuestions_ResponseMultiError(errors)
	}

	return nil
}

// ListQuestions_ResponseMultiError is an error wrapping multiple validation
// errors returned by ListQuestions_Response.ValidateAll() if the designated
// constraints aren't met.
type ListQuestions_ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQuestions_ResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQuestions_ResponseMultiError) AllErrors() []error { return m }

// ListQuestions_ResponseValidationError is the validation error returned by
// ListQuestions_Response.Validate if the designated constraints aren't met.
type ListQuestions_ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQuestions_ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQuestions_ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQuestions_ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQuestions_ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQuestions_ResponseValidationError) ErrorName() string {
	return "ListQuestions_ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListQuestions_ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQuestions_Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQuestions_ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQuestions_ResponseValidationError{}

// Validate checks the field values on Question_Content with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Question_Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Question_Content with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Question_ContentMultiError, or nil if none found.
func (m *Question_Content) ValidateAll() error {
	return m.validate(true)
}

func (m *Question_Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Text

	if m.Code != nil {
		// no validation rules for Code
	}

	if len(errors) > 0 {
		return Question_ContentMultiError(errors)
	}

	return nil
}

// Question_ContentMultiError is an error wrapping multiple validation errors
// returned by Question_Content.ValidateAll() if the designated constraints
// aren't met.
type Question_ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Question_ContentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Question_ContentMultiError) AllErrors() []error { return m }

// Question_ContentValidationError is the validation error returned by
// Question_Content.Validate if the designated constraints aren't met.
type Question_ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Question_ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Question_ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Question_ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Question_ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Question_ContentValidationError) ErrorName() string { return "Question_ContentValidationError" }

// Error satisfies the builtin error interface
func (e Question_ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuestion_Content.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Question_ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Question_ContentValidationError{}

// Validate checks the field values on Question_MultipleChoiceAnswer with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Question_MultipleChoiceAnswer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Question_MultipleChoiceAnswer with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// Question_MultipleChoiceAnswerMultiError, or nil if none found.
func (m *Question_MultipleChoiceAnswer) ValidateAll() error {
	return m.validate(true)
}

func (m *Question_MultipleChoiceAnswer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Question_MultipleChoiceAnswerMultiError(errors)
	}

	return nil
}

// Question_MultipleChoiceAnswerMultiError is an error wrapping multiple
// validation errors returned by Question_MultipleChoiceAnswer.ValidateAll()
// if the designated constraints aren't met.
type Question_MultipleChoiceAnswerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Question_MultipleChoiceAnswerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Question_MultipleChoiceAnswerMultiError) AllErrors() []error { return m }

// Question_MultipleChoiceAnswerValidationError is the validation error
// returned by Question_MultipleChoiceAnswer.Validate if the designated
// constraints aren't met.
type Question_MultipleChoiceAnswerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Question_MultipleChoiceAnswerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Question_MultipleChoiceAnswerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Question_MultipleChoiceAnswerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Question_MultipleChoiceAnswerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Question_MultipleChoiceAnswerValidationError) ErrorName() string {
	return "Question_MultipleChoiceAnswerValidationError"
}

// Error satisfies the builtin error interface
func (e Question_MultipleChoiceAnswerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuestion_MultipleChoiceAnswer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Question_MultipleChoiceAnswerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Question_MultipleChoiceAnswerValidationError{}

// Validate checks the field values on Question_FreeTextAnswer with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Question_FreeTextAnswer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Question_FreeTextAnswer with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Question_FreeTextAnswerMultiError, or nil if none found.
func (m *Question_FreeTextAnswer) ValidateAll() error {
	return m.validate(true)
}

func (m *Question_FreeTextAnswer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Question_FreeTextAnswerMultiError(errors)
	}

	return nil
}

// Question_FreeTextAnswerMultiError is an error wrapping multiple validation
// errors returned by Question_FreeTextAnswer.ValidateAll() if the designated
// constraints aren't met.
type Question_FreeTextAnswerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Question_FreeTextAnswerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Question_FreeTextAnswerMultiError) AllErrors() []error { return m }

// Question_FreeTextAnswerValidationError is the validation error returned by
// Question_FreeTextAnswer.Validate if the designated constraints aren't met.
type Question_FreeTextAnswerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Question_FreeTextAnswerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Question_FreeTextAnswerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Question_FreeTextAnswerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Question_FreeTextAnswerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Question_FreeTextAnswerValidationError) ErrorName() string {
	return "Question_FreeTextAnswerValidationError"
}

// Error satisfies the builtin error interface
func (e Question_FreeTextAnswerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuestion_FreeTextAnswer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Question_FreeTextAnswerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Question_FreeTextAnswerValidationError{}
